### ISSUE TITLE
fcb rename wildcard expansion

### ISSUE THREAD

**Issue by andrewbird** [stsp/fdpp#44]
As per PR #42, for which I've lost interest in fixing, here are the test binaries.[fcb_rename.zip](https://github.com/stsp/fdpp/files/2669878/fcb_rename.zip)

**Comment by stsp** [comment]
[0001-fcb-expand-wildcards-in-dst-name-fixes-44.patch.gz](https://github.com/stsp/fdpp/files/2755739/0001-fcb-expand-wildcards-in-dst-name-fixes-44.patch.gz)

Could you please try this patch?

**Comment by andrewbird** [comment]
Sure thing, there's been a couple or three times lately when I should have tested FDPP things for you, but I'm having a little trouble with my out of the ordinary testing environment, see #47

**Comment by andrewbird** [comment]
I constructed a proper reply yesterday, but forgot to press send :smile:, anyway it doesn't rename anything for me, either on MFS or FAT. Here are the errors (fixed the formatting on 1st FAT and MFS test). Did the tests work for you?
~~~
======================================================================
FAIL: Test PP-DOS-GIT FAT FCB file rename wildcard one
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1568, in test_fat_fcb_rename_wild_1
    self._test_fcb_rename_common("FAT", "wild_one")
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1498, in _test_fcb_rename_common
    self.assertIn("Rename Operation Success", results);
AssertionError: 'Rename Operation Success' not found in 'test_mfs.bat\r\n
C:\\>d:\r\n
D:\\>c:\\mfsfcbr4\r\n
Rename Operation Failed
D:\\>DIR\r\n
 Volume in drive D has no label\r\n
 Volume Serial Number is 1234-5678\r\n
 Directory of D:\\\r\n
\r\n
THREE    IN              7  01-16-87  2:41p\r\n
ONE      IN              7  01-16-87  2:41p\r\n
FIVE     IN              7  01-16-87  2:41p\r\n
TWO      IN              7  01-16-87  2:41p\r\n
FOUR     IN              7  01-16-87  2:41p\r\n
NONE     CTL             7  01-16-87  2:41p\r\n
         6 file(s)             42 bytes\r\n         0 dir(s)      10,592,256 bytes free\r\n
D:\\>'

======================================================================
FAIL: Test PP-DOS-GIT FAT FCB file rename wildcard two
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1578, in test_fat_fcb_rename_wild_2
    self._test_fcb_rename_common("FAT", "wild_two")
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1507, in _test_fcb_rename_common
    self.assertIn("Rename Operation Success", results);
AssertionError: 'Rename Operation Success' not found in 'test_mfs.bat\r\nC:\\>d:\r\nD:\\>c:\\mfsfcbr5\r\nRename Operation FailedD:\\>DIR\r\n Volume in drive D has no label\r\n Volume Serial Number is 1234-5678\r\n Directory of D:\\\r\n\r\nATHREE   IN              7  01-16-87  2:41p\r\nAFIVE    IN              7  01-16-87  2:41p\r\nXNONE    CTL             7  01-16-87  2:41p\r\nAFOUR    IN              7  01-16-87  2:41p\r\nATWO     IN              7  01-16-87  2:41p\r\nAONE     IN              7  01-16-87  2:41p\r\n         6 file(s)             42 bytes\r\n         0 dir(s)      10,592,256 bytes free\r\nD:\\>'

======================================================================
FAIL: Test PP-DOS-GIT FAT FCB file rename wildcard three
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1588, in test_fat_fcb_rename_wild_3
    self._test_fcb_rename_common("FAT", "wild_three")
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1516, in _test_fcb_rename_common
    self.assertIn("Rename Operation Success", results);
AssertionError: 'Rename Operation Success' not found in 'test_mfs.bat\r\nC:\\>d:\r\nD:\\>c:\\mfsfcbr6\r\nRename Operation FailedD:\\>DIR\r\n Volume in drive D has no label\r\n Volume Serial Number is 1234-5678\r\n Directory of D:\\\r\n\r\nABC003   TXT             7  01-16-87  2:41p\r\nABC004   TXT             7  01-16-87  2:41p\r\nXBC007   TXT             7  01-16-87  2:41p\r\nABC010   TXT             7  01-16-87  2:41p\r\nABC002   TXT             7  01-16-87  2:41p\r\nABC005   TXT             7  01-16-87  2:41p\r\nABC001   TXT             7  01-16-87  2:41p\r\n         7 file(s)             49 bytes\r\n         0 dir(s)      10,588,160 bytes free\r\nD:\\>'

======================================================================
FAIL: Test PP-DOS-GIT FAT FCB file rename wildcard four
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1598, in test_fat_fcb_rename_wild_4
    self._test_fcb_rename_common("FAT", "wild_four")
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1526, in _test_fcb_rename_common
    self.assertIn("Rename Operation Success", results);
AssertionError: 'Rename Operation Success' not found in 'test_mfs.bat\r\nC:\\>d:\r\nD:\\>c:\\mfsfcbr7\r\nRename Operation FailedD:\\>DIR\r\n Volume in drive D has no label\r\n Volume Serial Number is 1234-5678\r\n Directory of D:\\\r\n\r\nABC004   HTM             7  01-16-87  2:41p\r\nABC002   HTM             7  01-16-87  2:41p\r\nABC003   HTM             7  01-16-87  2:41p\r\nABC010   HTM             7  01-16-87  2:41p\r\nABC001   HTM             7  01-16-87  2:41p\r\nXBC007   HTM             7  01-16-87  2:41p\r\nABC005   HTM             7  01-16-87  2:41p\r\n         7 file(s)             49 bytes\r\n         0 dir(s)      10,588,160 bytes free\r\nD:\\>'

======================================================================
FAIL: Test PP-DOS-GIT MFS FCB file rename wildcard one
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1573, in test_mfs_fcb_rename_wild_1
    self._test_fcb_rename_common("MFS", "wild_one")
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1498, in _test_fcb_rename_common
    self.assertIn("Rename Operation Success", results);
AssertionError: 'Rename Operation Success' not found in 'test_mfs.bat\r\n
C:\\>d:\r\n
D:\\>c:\\mfsfcbr4\r\n
Rename Operation FailedD:\\>DIR\r\n
 Volume in drive D is IR DXXXXS D\r\n
 Directory of D:\\\r\n
\r\n
THREE    IN              7  01-16-19  2:42p\r\n
ONE      IN              7  01-16-19  2:42p\r\n
FIVE     IN              7  01-16-19  2:42p\r\n
TWO      IN              7  01-16-19  2:42p\r\n
FOUR     IN              7  01-16-19  2:42p\r\n
NONE     CTL             7  01-16-19  2:42p\r\n
         6 file(s)             42 bytes\r\n         0 dir(s)     38,232 Mega bytes free\r\n
D:\\>'

======================================================================
FAIL: Test PP-DOS-GIT MFS FCB file rename wildcard two
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1583, in test_mfs_fcb_rename_wild_2
    self._test_fcb_rename_common("MFS", "wild_two")
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1507, in _test_fcb_rename_common
    self.assertIn("Rename Operation Success", results);
AssertionError: 'Rename Operation Success' not found in 'test_mfs.bat\r\nC:\\>d:\r\nD:\\>c:\\mfsfcbr5\r\nRename Operation FailedD:\\>DIR\r\n Volume in drive D is IR DXXXXS D\r\n Directory of D:\\\r\n\r\nATHREE   IN              7  01-16-19  2:42p\r\nAFIVE    IN              7  01-16-19  2:42p\r\nXNONE    CTL             7  01-16-19  2:42p\r\nAFOUR    IN              7  01-16-19  2:42p\r\nATWO     IN              7  01-16-19  2:42p\r\nAONE     IN              7  01-16-19  2:42p\r\n         6 file(s)             42 bytes\r\n         0 dir(s)     38,232 Mega bytes free\r\nD:\\>'

======================================================================
FAIL: Test PP-DOS-GIT MFS FCB file rename wildcard three
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1593, in test_mfs_fcb_rename_wild_3
    self._test_fcb_rename_common("MFS", "wild_three")
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1516, in _test_fcb_rename_common
    self.assertIn("Rename Operation Success", results);
AssertionError: 'Rename Operation Success' not found in 'test_mfs.bat\r\nC:\\>d:\r\nD:\\>c:\\mfsfcbr6\r\nRename Operation FailedD:\\>DIR\r\n Volume in drive D is IR DXXXXS D\r\n Directory of D:\\\r\n\r\nABC003   TXT             7  01-16-19  2:42p\r\nABC004   TXT             7  01-16-19  2:42p\r\nXBC007   TXT             7  01-16-19  2:42p\r\nABC010   TXT             7  01-16-19  2:42p\r\nABC002   TXT             7  01-16-19  2:42p\r\nABC005   TXT             7  01-16-19  2:42p\r\nABC001   TXT             7  01-16-19  2:42p\r\n         7 file(s)             49 bytes\r\n         0 dir(s)     38,232 Mega bytes free\r\nD:\\>'

======================================================================
FAIL: Test PP-DOS-GIT MFS FCB file rename wildcard four
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1603, in test_mfs_fcb_rename_wild_4
    self._test_fcb_rename_common("MFS", "wild_four")
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1526, in _test_fcb_rename_common
    self.assertIn("Rename Operation Success", results);
AssertionError: 'Rename Operation Success' not found in 'test_mfs.bat\r\nC:\\>d:\r\nD:\\>c:\\mfsfcbr7\r\nRename Operation FailedD:\\>DIR\r\n Volume in drive D is IR DXXXXS D\r\n Directory of D:\\\r\n\r\nABC004   HTM             7  01-16-19  2:42p\r\nABC002   HTM             7  01-16-19  2:42p\r\nABC003   HTM             7  01-16-19  2:42p\r\nABC010   HTM             7  01-16-19  2:42p\r\nABC001   HTM             7  01-16-19  2:42p\r\nXBC007   HTM             7  01-16-19  2:42p\r\nABC005   HTM             7  01-16-19  2:42p\r\n         7 file(s)             49 bytes\r\n         0 dir(s)     38,232 Mega bytes free\r\nD:\\>'

----------------------------------------------------------------------
Ran 60 tests in 249.556s

FAILED (SKIP=7, failures=8)
~~~

**Comment by stsp** [comment]
[0001-fcb-expand-wildcards-in-dst-name-fixes-44.patch.gz](https://github.com/stsp/fdpp/files/2766358/0001-fcb-expand-wildcards-in-dst-name-fixes-44.patch.gz)
Please try this one.

**Comment by andrewbird** [comment]
It looks like the extension is missing
~~~
ajb@polly:/clients/common/dosemu2.git$ nosetests -v test/test_bootos.py:PPDOSGITTestCase.test_fat_fcb_rename_wild_1
Test PP-DOS-GIT FAT FCB file rename wildcard one ... FAIL

======================================================================
FAIL: Test PP-DOS-GIT FAT FCB file rename wildcard one
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1566, in test_fat_fcb_rename_wild_1
    self._test_fcb_rename_common("FAT", "wild_one")
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1497, in _test_fcb_rename_common
    assertIsPresent(testdir, results, fstype, "one", "out", "File not renamed")
  File "/clients/common/dosemu2.git/test/test_bootos.py", line 1463, in assertIsPresent
    self.assertIn("\n{:<8} {:<3}".format(f,e).upper(), results.upper())
AssertionError: '\nONE      OUT' not found in 'TEST_MFS.BAT\r\n
C:\\>D:\r\n
D:\\>C:\\MFSFCBR4\r\n
RENAME OPERATION SUCCESS
D:\\>DIR\r\n
 VOLUME IN DRIVE D HAS NO LABEL\r\n
 VOLUME SERIAL NUMBER IS 1234-5678\r\n
 DIRECTORY OF D:\\\r\n
\r\n
THREE                    7  01-18-19 11:19A\r\n
ONE                      7  01-18-19 11:19A\r\n
FIVE                     7  01-18-19 11:19A\r\n
TWO                      7  01-18-19 11:19A\r\n
FOUR                     7  01-18-19 11:19A\r\n
NONE     CTL             7  01-18-19 11:19A\r\n
         6 FILE(S)             42 BYTES\r\n         0 DIR(S)      10,592,256 BYTES FREE\r\n
D:\\>'

----------------------------------------------------------------------
Ran 1 test in 3.999s

FAILED (failures=1)
~~~

**Comment by andrewbird** [comment]
Looks good to me!
~~~
$ nosetests -v test/test_bootos.py:PPDOSGITTestCase
Test PP-DOS-GIT FAT12 image file ... SKIP: Booting from image not supported
Test PP-DOS-GIT FAT12 image file D writable ... ok
Test PP-DOS-GIT FAT12 vfs directory ... ok
Test PP-DOS-GIT FAT12 vfs directory boot.blk ... SKIP: Not supported by Boot Block
Test PP-DOS-GIT FAT16 image file ... SKIP: Booting from image not supported
Test PP-DOS-GIT FAT16 image file D writable ... ok
Test PP-DOS-GIT FAT16 vfs directory ... ok
Test PP-DOS-GIT FAT16 vfs directory boot.blk ... SKIP: Not supported by Boot Block
Test PP-DOS-GIT FAT16B image file ... SKIP: Booting from image not supported
Test PP-DOS-GIT FAT16B vfs directory ... ok
Test PP-DOS-GIT FAT16B vfs directory boot.blk ... SKIP: Not supported by Boot Block
Test PP-DOS-GIT FAT32 disk info ... ok
Test PP-DOS-GIT FAT FCB file rename simple ... ok
Test PP-DOS-GIT FAT FCB file rename source missing ... ok
Test PP-DOS-GIT FAT FCB file rename target exists ... ok
Test PP-DOS-GIT FAT FCB file rename wildcard one ... ok
Test PP-DOS-GIT FAT FCB file rename wildcard two ... ok
Test PP-DOS-GIT FAT FCB file rename wildcard three ... ok
Test PP-DOS-GIT FAT FCB file rename wildcard four ... ok
Test PP-DOS-GIT FAT AUTO vfs directory ... ok
Test PP-DOS-GIT Floppy image file ... SKIP: Booting from image not supported
Test PP-DOS-GIT Floppy vfs directory ... ok
Test PP-DOS-GIT INT21 disk info ... ok
Test PP-DOS-GIT LFN volume info on FAT(img) ... ok
Test PP-DOS-GIT LFN volume info on MFS ... ok
Test PP-DOS-GIT MFS auto hd vfs directory redirection ... ok
Test PP-DOS-GIT MFS FCB file rename simple ... ok
Test PP-DOS-GIT MFS FCB file rename source missing ... ok
Test PP-DOS-GIT MFS FCB file rename target exists ... ok
Test PP-DOS-GIT MFS FCB file rename wildcard one ... ok
Test PP-DOS-GIT MFS FCB file rename wildcard two ... ok
Test PP-DOS-GIT MFS FCB file rename wildcard three ... ok
Test PP-DOS-GIT MFS FCB file rename wildcard four ... ok
Test PP-DOS-GIT MFS LFN directory change current ... ok
Test PP-DOS-GIT MFS LFN directory create ... ok
Test PP-DOS-GIT MFS LFN directory delete ... ok
Test PP-DOS-GIT MFS LFN directory delete not empty ... ok
Test PP-DOS-GIT MFS LFN file append ... ok
Test PP-DOS-GIT MFS LFN file create ... ok
Test PP-DOS-GIT MFS LFN file create readonly ... ok
Test PP-DOS-GIT MFS LFN file find ... ok
Test PP-DOS-GIT MFS LFN file read ... ok
Test PP-DOS-GIT MFS LFN file truncate ... ok
Test PP-DOS-GIT MFS LFN get current directory ... ok
Test PP-DOS-GIT MFS LFN Truename ... ok
Test PP-DOS-GIT MFS lredir2 command redirection ... ok
Test PP-DOS-GIT MFS SFN directory change current ... ok
Test PP-DOS-GIT MFS SFN directory create ... ok
Test PP-DOS-GIT MFS SFN directory delete ... ok
Test PP-DOS-GIT MFS SFN directory delete not empty ... ok
Test PP-DOS-GIT MFS SFN file append ... ok
Test PP-DOS-GIT MFS SFN file create ... ok
Test PP-DOS-GIT MFS SFN file create readonly ... ok
Test PP-DOS-GIT MFS SFN file find ... ok
Test PP-DOS-GIT MFS SFN file read ... ok
Test PP-DOS-GIT MFS SFN file truncate ... ok
Test PP-DOS-GIT MFS SFN get current directory ... ok
Test PP-DOS-GIT MFS SFN Truename ... ok
Test PP-DOS-GIT SysType ... ok
Test PP-DOS-GIT Three vfs directories configured ... ok

----------------------------------------------------------------------
Ran 60 tests in 249.676s

OK (SKIP=7)
~~~

**Comment by stsp** [comment]
Force-pushed a slightly better version.
So looks like the list of freedos bugs is now empty?

**Comment by andrewbird** [comment]
Retested, it's still passing. There are probably more bugs in freedos, I haven't added any tests to the suite lately, there didn't seem much point. I may look at adding some more soon.

**Comment by stsp** [comment]
Well, indeed it might be better to not dive into
a freedos bugs just yet. Only those important
for dosemu should be considered. Maybe sometime
later we fix all of them, but right now its too early
to look through freedos bugzilla, or we can never
get to anything useful.
So lets just pretend there are no bugs. :)

**Comment by stsp** [comment]
But if you are going to add tests that are not
based on freedos bugzilla (so not a 100% chance
of hitting a freedos bug but a good chance of hitting
an fdpp bug), then you are of course welcome. :)
